[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "eval"
version = "0.1.0"
description = "Evaluation framework for web scraping methods"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate==1.10.0",
    "aiofiles==24.1.0",
    "aiohappyeyeballs==2.6.1",
    "aiohttp==3.12.15",
    "aiosignal==1.4.0",
    "annotated-types==0.7.0",
    "anyio==4.10.0",
    "anytree==2.13.0",
    "astor==0.8.1",
    "asttokens==3.0.0",
    "attrs==25.3.0",
    "babel==2.17.0",
    "beautifulsoup4==4.13.4",
    "bitsandbytes==0.47.0",
    "blake3==1.0.5",
    "brotli==1.1.0",
    "bs4==0.0.2",
    "cachetools==5.5.2",
    "cbor2==5.7.0",
    "celery>=5.5.3",
    "certifi==2025.8.3",
    "cffi==1.17.1",
    "charset-normalizer==3.4.3",
    "click==8.2.1",
    "cloudpickle==3.1.1",
    "comm==0.2.3",
    "compressed-tensors==0.10.2",
    "courlan==1.3.2",
    "cssutils==2.11.1",
    "cupy-cuda12x==13.5.1",
    "dataclasses-json==0.6.7",
    "datasets==4.0.0",
    "dateparser==1.2.2",
    "debugpy==1.8.16",
    "decorator==5.2.1",
    "depyf==0.19.0",
    "dill==0.3.8",
    "diskcache==5.6.3",
    "distro==1.9.0",
    "dnspython==2.7.0",
    "docling==2.43.0",
    "docling-core==2.44.1",
    "docling-ibm-models==3.9.0",
    "docling-parse==4.1.0",
    "easyocr==1.7.2",
    "einops==0.8.1",
    "email-validator==2.2.0",
    "et-xmlfile==2.0.0",
    "executing==2.2.0",
    "faiss-cpu==1.11.0.post1",
    "fastapi==0.116.1",
    "fastapi-cli==0.0.8",
    "fastapi-cloud-cli==0.1.5",
    "fastrlock==0.8.3",
    "ffmpy==0.6.1",
    "filelock==3.18.0",
    "filetype==1.2.0",
    "frozenlist==1.7.0",
    "fsspec==2025.3.0",
    "fuzzywuzzy==0.18.0",
    "gguf==0.17.1",
    "google-auth==2.40.3",
    "google-genai==1.29.0",
    "gradio==5.42.0",
    "gradio-client==1.11.1",
    "greenlet==3.2.4",
    "groovy==0.1.2",
    "h11==0.16.0",
    "hf-xet==1.1.7",
    "html-chunking==0.0.4",
    "html2text==2025.4.15",
    "html5lib==1.1",
    "htmldate==1.9.3",
    "htmlrag==0.1.1",
    "httpcore==1.0.9",
    "httptools==0.6.4",
    "httpx==0.28.1",
    "httpx-sse==0.4.1",
    "huggingface-hub==0.34.4",
    "idna==3.10",
    "imageio==2.37.0",
    "inscriptis==2.6.0",
    "interegular==0.3.3",
    "ipykernel==6.30.1",
    "ipython==9.4.0",
    "ipython-pygments-lexers==1.1.1",
    "ipywidgets==8.1.7",
    "jedi==0.19.2",
    "jinja2==3.1.6",
    "jiter==0.10.0",
    "joblib==1.5.1",
    "json-repair==0.49.0",
    "jsonlines==3.1.0",
    "jsonpatch==1.33",
    "jsonpointer==3.0.0",
    "jsonref==1.1.0",
    "jsonschema==4.25.0",
    "jsonschema-specifications==2025.4.1",
    "jupyter-client==8.6.3",
    "jupyter-core==5.8.1",
    "jupyterlab-widgets==3.0.15",
    "justext==3.0.2",
    "langchain==0.3.27",
    "langchain-community==0.3.27",
    "langchain-core==0.3.74",
    "langchain-huggingface==0.3.1",
    "langchain-nvidia-ai-endpoints==0.3.16",
    "langchain-text-splitters==0.3.9",
    "langsmith==0.4.13",
    "lark==1.2.2",
    "latex2mathml==3.78.0",
    "lazy-loader==0.4",
    "llguidance==0.7.30",
    "llvmlite==0.44.0",
    "lm-format-enforcer==0.10.12",
    "lxml==5.4.0",
    "lxml-html-clean==0.4.2",
    "markdown-it-py==4.0.0",
    "markdownify==1.2.0",
    "marko==2.2.0",
    "markupsafe==3.0.2",
    "marshmallow==3.26.1",
    "matplotlib-inline==0.1.7",
    "mcp==1.10.1",
    "mdurl==0.1.2",
    "mistral-common==1.8.3",
    "more-itertools==10.7.0",
    "mpire==2.10.2",
    "mpmath==1.3.0",
    "msgpack==1.1.1",
    "msgspec==0.19.0",
    "multidict==6.6.4",
    "multiprocess==0.70.16",
    "mypy-extensions==1.1.0",
    "nest-asyncio==1.6.0",
    "networkx==3.5",
    "ninja==1.13.0",
    "numba==0.61.2",
    "numpy==2.2.6",
    "nvidia-cublas-cu12==12.6.4.1",
    "nvidia-cuda-cupti-cu12==12.6.80",
    "nvidia-cuda-nvrtc-cu12==12.6.77",
    "nvidia-cuda-runtime-cu12==12.6.77",
    "nvidia-cudnn-cu12==9.5.1.17",
    "nvidia-cufft-cu12==11.3.0.4",
    "nvidia-cufile-cu12==1.11.1.6",
    "nvidia-curand-cu12==10.3.7.77",
    "nvidia-cusolver-cu12==11.7.1.2",
    "nvidia-cusparse-cu12==12.5.4.2",
    "nvidia-cusparselt-cu12==0.6.3",
    "nvidia-nccl-cu12==2.26.2",
    "nvidia-nvjitlink-cu12==12.6.85",
    "nvidia-nvtx-cu12==12.6.77",
    "openai==1.90.0",
    "opencv-python-headless==4.11.0.86",
    "openpyxl==3.1.5",
    "orjson==3.11.1",
    "outlines-core==0.2.10",
    "packaging==25.0",
    "pandas==2.3.1",
    "parso==0.8.4",
    "partial-json-parser==0.2.1.1.post6",
    "pdfkit==1.0.0",
    "pexpect==4.9.0",
    "pillow==11.3.0",
    "platformdirs==4.3.8",
    "pluggy==1.6.0",
    "polars==1.32.3",
    "prometheus-client==0.22.1",
    "prometheus-fastapi-instrumentator==7.1.0",
    "prompt-toolkit==3.0.51",
    "propcache==0.3.2",
    "protobuf==6.32.0",
    "psutil==7.0.0",
    "ptyprocess==0.7.0",
    "pure-eval==0.2.3",
    "py-cpuinfo==9.0.0",
    "pyarrow==21.0.0",
    "pyasn1==0.6.1",
    "pyasn1-modules==0.4.2",
    "pybase64==1.4.2",
    "pyclipper==1.3.0.post6",
    "pycountry==24.6.1",
    "pycparser==2.22",
    "pydantic==2.11.7",
    "pydantic-core==2.33.2",
    "pydantic-extra-types==2.10.5",
    "pydantic-settings==2.10.1",
    "pydub==0.25.1",
    "pygments==2.19.2",
    "pylatexenc==2.10",
    "pypdfium2==4.30.0",
    "python-bidi==0.6.6",
    "python-dateutil==2.9.0.post0",
    "python-docx==1.2.0",
    "python-dotenv==1.1.1",
    "python-json-logger==3.3.0",
    "python-multipart==0.0.20",
    "python-pptx==1.0.2",
    "pytz==2025.2",
    "pyyaml==6.0.2",
    "pyzmq==27.0.1",
    "rapidfuzz==3.13.0",
    "ray==2.48.0",
    "readabilipy==0.3.0",
    "referencing==0.36.2",
    "regex==2025.7.34",
    "requests==2.32.4",
    "requests-toolbelt==1.0.0",
    "rich==14.1.0",
    "rich-toolkit==0.15.0",
    "rignore==0.6.4",
    "rpds-py==0.27.0",
    "rsa==4.9.1",
    "rtree==1.4.0",
    "ruff==0.12.8",
    "safehttpx==0.1.6",
    "safetensors==0.6.2",
    "scikit-image==0.25.2",
    "scikit-learn==1.7.1",
    "scipy==1.16.1",
    "semantic-version==2.10.0",
    "semchunk==2.2.2",
    "sentence-transformers==5.1.0",
    "sentencepiece==0.2.1",
    "sentry-sdk==2.35.0",
    "shapely==2.1.1",
    "shellingham==1.5.4",
    "six==1.17.0",
    "sniffio==1.3.1",
    "soundfile==0.13.1",
    "soupsieve==2.7",
    "soxr==0.5.0.post1",
    "sqlalchemy==2.0.43",
    "sse-starlette==3.0.2",
    "stack-data==0.6.3",
    "starlette==0.47.2",
    "sympy==1.14.0",
    "tabulate==0.9.0",
    "tenacity==9.1.2",
    "threadpoolctl==3.6.0",
    "tifffile==2025.6.11",
    "tiktoken==0.11.0",
    "tld==0.13.1",
    "tokenizers==0.21.4",
    "tomlkit==0.13.3",
    "torch==2.7.1",
    "torchaudio==2.7.1",
    "torchvision==0.22.1",
    "tornado==6.5.2",
    "tqdm==4.67.1",
    "trafilatura==2.0.0",
    "traitlets==5.14.3",
    "transformers==4.55.0",
    "triton==3.3.1",
    "typer==0.16.0",
    "typing-extensions==4.14.1",
    "typing-inspect==0.9.0",
    "typing-inspection==0.4.1",
    "tzdata==2025.2",
    "tzlocal==5.3.1",
    "urllib3==2.5.0",
    "uvicorn==0.35.0",
    "uvloop==0.21.0",
    "vllm==0.10.0",
    "watchfiles==1.1.0",
    "wcwidth==0.2.13",
    "webencodings==0.5.1",
    "websockets==15.0.1",
    "widgetsnbextension==4.0.14",
    "xformers==0.0.31",
    "xgrammar==0.1.21",
    "xlsxwriter==3.2.5",
    "xxhash==3.5.0",
    "yarl==1.20.1",
    "zstandard==0.23.0",
]



[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["eval*"]
